// src/pages/ConfigPage.vue
<template>
  <div id="customConfigPage">
    <h2>
      自定义难度
      <a-button style="float: right" @click="doBack">返回</a-button>
    </h2>
    <a-form
      ref="formRef"
      label-align="left"
      :label-col="{ style: { width: '120px' } }"
      :model="config"
      @finish="handleFinish"
    >
      <a-form-item label="槽容量" name="slotNum">
        <a-input-number v-model:value="config.slotNum" />
      </a-form-item>
      <a-form-item label="合成数" name="composeNum">
        <a-input-number v-model:value="config.composeNum" />
      </a-form-item>
      <a-form-item label="动物数" name="typeNum">
        <a-input-number v-model:value="config.typeNum" />
      </a-form-item>
      <a-form-item label="动物图案" name="animalStr">
        <a-input v-model:value="config.animalStr" />
      </a-form-item>
      <a-form-item label="总层数" name="levelNum">
        <a-input-number v-model:value="config.levelNum" />
      </a-form-item>
      <a-form-item label="每层块数" name="levelBlockNum">
        <a-input-number v-model:value="config.levelBlockNum" />
      </a-form-item>
      <a-form-item label="边界收缩" name="borderStep">
        <a-input-number v-model:value="config.borderStep" />
      </a-form-item>
      <a-form-item label="随机区数" name="randomAreaNum">
        <a-input-number v-model:value="config.randomAreaNum" />
      </a-form-item>
      <a-form-item label="随机区块数" name="randomBlockNum">
        <a-input-number v-model:value="config.randomBlockNum" />
      </a-form-item>
      <a-form-item>
        <a-button
          type="primary"
          html-type="submit"
          style="margin-bottom: 12px"
          block
        >
          开始
        </a-button>
        <a-button block style="margin-bottom: 12px" @click="resetForm"
          >重置
        </a-button>
        <a-button block danger @click="resetConfig">还原最初配置</a-button>
      </a-form-item>
    </a-form>
  </div>
</template>
<script setup lang="ts">
import { reactive, ref } from "vue";
import { FormInstance } from "ant-design-vue";
import { useRouter } from "vue-router";
import { useGlobalStore } from "../core/globalStore";
import { defaultGameConfig } from "../core/gameConfig";

const formRef = ref<FormInstance>();
const router = useRouter();
const { customConfig, setGameConfig, setCustomConfig, reset } =
  useGlobalStore();
const initConfig = {
  randomAreaNum: 2,
  randomBlockNum: 8,
  animalStr: defaultGameConfig.animals.join(""),
  ...customConfig,
};
const config = reactive<any>(initConfig);

/**
 * 表单提交
 * @param values
 */
const handleFinish = (values: any) => {
  config.randomBlocks = new Array(values.randomAreaNum).fill(
    values.randomBlockNum
  );
  if (values.animalStr) {
    config.animals = Array.from(values.animalStr);
  }
  setGameConfig(config);
  setCustomConfig(config);
  router.push("/game");
};

const resetForm = () => {
  formRef?.value?.resetFields();
};

/**
 * 还原至初始配置
 */
const resetConfig = () => {
  reset();
  router.go(0);
};

/**
 * 回上一页
 */
const doBack = () => {
  router.back();
};
</script>
<style></style>

// react/src/views/ConfigPage.tsx
import styled from '@emotion/styled'
import Title from '../components/Title'
import { Button, Form, InputNumber, Select, Image, Tooltip } from 'antd'
import { useNavigate } from 'react-router-dom'
import { materialList } from '../core/gameConfig'
import { useEffect, useState } from 'react'
import GameConfigStore from '../store/store'
const StyleConfigPage = styled.div`
    padding: 5px;
`

const { Item } = Form
const { Option } = Select
const StyleTitle = styled(Title)({
    '&::before,&::after': {
        clear: 'both',
        display: 'block',
        content: '""'
    }
})
const StyleButton = styled(Button)({
    float: 'right'
})

const StyleInputNumber = styled(InputNumber)({
    'width': "100%"
})

const StyleFooterButton = styled(Button)({
    marginBottom: 16
})
const ConfigPage = () => {
    const navigate = useNavigate()
    const [form] = Form.useForm()
    const { config: { customGameConfig },reset,updateConfig } = GameConfigStore.useModel()
    const setFormConfig = (config: GameConfigType) => {
        const { materialList: configMaterialList, ...rest } = config
        return {
            ...rest, 
            materialNum: configMaterialList.map(item => item.value),
            randomAreaNum: 2,
            randomBlockNum: 8,
        }
    }
    const [customFormConfig,setCustomFormConfig] = useState(setFormConfig(customGameConfig))
    useEffect(() => {
        setCustomFormConfig(setFormConfig(customGameConfig))
    },[customGameConfig])
    const goBack = () => {
        navigate(-1);
    }
    const onFinishHandler = () => {
        const config = form.getFieldsValue(true);
        config.materialList = config.materialNum.map((key: string) => materialList.find(item => item.value === key));
        delete config.materialNum;
        updateConfig({
            gameConfig: config,
            customGameConfig: config
        });
        navigate('/game');
    }
    return (
        <StyleConfigPage>
            <StyleTitle level={2}>
                自定义难度
                <StyleButton onClick={goBack}>返回</StyleButton>
            </StyleTitle>
            <Form
                autoComplete="off"
                label-align="left"
                labelCol={{ span: 4 }}
                onFinish={onFinishHandler}
                form={form}
                initialValues={customFormConfig}
            >
                <Item label="槽容量" name="slotNum">
                    <StyleInputNumber />
                </Item>
                <Item label="合成数" name="composeNum">
                    <StyleInputNumber />
                </Item>
                <Item label="素材类别数" name="materialTypeNum">
                    <StyleInputNumber />
                </Item>
                <Item label="素材列表" name="materialNum">
                    <Select mode='multiple'>
                        {
                            materialList.map((item, index) => (
                                <Option key={`${item.value}-${index}`} value={item.value}>
                                    <Tooltip title={item.label} placement="leftTop">
                                        <Image src={item.value} width={40} height={40}></Image>
                                    </Tooltip>
                                </Option>
                            ))
                        }
                    </Select>
                </Item>
                <Item label="总层数" name="levelNum">
                    <StyleInputNumber />
                </Item>
                <Item label="每层块数" name="levelBlockNum">
                    <StyleInputNumber />
                </Item>
                <Item label="边界收缩" name="borderStep">
                    <StyleInputNumber />
                </Item>
                <Item label="随机区数" name="randomAreaNum">
                    <StyleInputNumber />
                </Item>
                <Item label="随机区块数" name="randomBlockNum">
                    <StyleInputNumber />
                </Item>
                <Item>
                    <StyleFooterButton htmlType='submit' block>开始</StyleFooterButton>
                    <StyleFooterButton block onClick={() => form.resetFields()}>重置</StyleFooterButton>
                    <Button danger block onClick={reset}>还原初始配置</Button>
                </Item>
            </Form>
        </StyleConfigPage>
    )
}

export default ConfigPage
